# Visit https://github.com/lowlighter/metrics#-documentation for full reference

name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 2 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:

  github-metrics:
    name: Metrics
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Gakk
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Oslo
          config_octicon: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          plugin_sponsorships: yes
          plugin_sponsorships_sections: sponsorships
          plugin_sponsorships_size: 24
